kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx
    role: green
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: green
  ports:
    - port: 80
      targetPort: 80